# Generated by Django 3.1.4 on 2020-12-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_model',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_type', models.TextField()),
                ('model_name', models.TextField()),
            ],
        ),
    ]
