# Generated by Django 3.1.3 on 2020-11-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='comp_branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, verbose_name='company address')),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100, verbose_name='company email')),
            ],
        ),
        migrations.CreateModel(
            name='car_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('ctype', models.CharField(max_length=20, verbose_name='car_type')),
                ('name', models.CharField(max_length=20, verbose_name='model name')),
                ('price', models.FloatField()),
                ('fuel', models.CharField(max_length=20, verbose_name='fuel type')),
                ('gear', models.CharField(max_length=20, verbose_name='gear type')),
                ('seat', models.CharField(max_length=20, verbose_name='seating')),
                ('mile', models.FloatField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='royal.comp_branch')),
            ],
        ),
    ]
